# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

softmax <- function(x) {
    .Call(`_LAMBDA_softmax`, x)
}

mixGaussEM <- function(Y, X, L, muini, betaini, Sigmaini, tau, nu, Lambda, num_iter) {
    .Call(`_LAMBDA_mixGaussEM`, Y, X, L, muini, betaini, Sigmaini, tau, nu, Lambda, num_iter)
}

mixtruncGaussEM <- function(Y, X, L, muini, betaini, Sigmaini, wini, tau, nu, Lambda, num_iter) {
    .Call(`_LAMBDA_mixtruncGaussEM`, Y, X, L, muini, betaini, Sigmaini, wini, tau, nu, Lambda, num_iter)
}

